[deployment]
[[deployment.rule]]
shard = "primary"
indexers = [ "index_node_cosmos_1" ]

[store]
[store.primary]
connection = "postgresql://nabarunsarkar:admin@localhost:5432/graph-node"
pool_size = 10

[chains]
ingestor = "block_ingestor_node"

[chains.cosmoshub-4]
shard = "primary"
protocol = "cosmos"
provider = [
    { label = "cosmoshub-4", details = { type = "firehose", url = "http://0.0.0.0:9030/" }},
]